Cast floats to ints for Qt
For some reason since recent Python versions (3.10?) some types have
changed somehow causing exceptions like the following

  TypeError: setInterval(self, int): argument 1 has unexpected type 'float'

Make sure to cast the numbers to ints before giving them to Qt.

Fixes #5